[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.dagster]
module_name = "tipping_point_uk_charity_bankers.definitions"
code_location_name = "tipping_point_uk_charity_bankers"
