# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/tipping-point-uk-charity-bankers',
                'doc_host': 'https://Autonomy-Data-Unit.github.io',
                'git_url': 'https://github.com/Autonomy-Data-Unit/tipping-point-uk-charity-bankers',
                'lib_path': 'tipping_point_uk_charity_bankers'},
  'syms': { 'tipping_point_uk_charity_bankers.assets': {},
            'tipping_point_uk_charity_bankers.core': { 'tipping_point_uk_charity_bankers.core.foo': ( 'core.html#foo',
                                                                                                      'tipping_point_uk_charity_bankers/core.py')},
            'tipping_point_uk_charity_bankers.definitions': {}}}
